const mongoose = require('mongoose');
require('dotenv').config();

const Product = require('./models/Product');
const connectDB = require('./config/db');
const Order = require('./models/Order');
const User = require('./models/User');

// ============ ВСЕ ТОВАРЫ ============
const products = [
  // ===== Oggo x Злая монашка Green 80mg =====
  {
    name: 'Oggo x Злая монашка Green - Монстр манго локо',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Манго',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Mango',
    description: 'Монстр манго локо - мощный фруктовый вкус',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Фреш яблоко апельсин',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Яблоко, апельсин',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Apple+Orange',
    description: 'Освежающий фреш яблоко с апельсином',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Тропический шот',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Тропический коктейль',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Tropical',
    description: 'Тропический шот - взрыв тропических вкусов',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Палпи гуава маракуйя',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Гуава, маракуйя',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Guava',
    description: 'Палпи гуава маракуйя - экзотический вкус',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Смузи тропический банан',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Банан, тропики',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Banana',
    description: 'Нежный смузи с тропическим бананом',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Токсичный киви',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Киви',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Kiwi',
    description: 'Токсичный киви - яркий киви с кислинкой',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Фруктовый бонпари',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Фруктовый микс',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Bonpari',
    description: 'Фруктовый бонпари - сладкий фруктовый вкус',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Скитлз тропики',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Скитлз, тропики',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Skittles',
    description: 'Скитлз тропики - вкус тропических конфет',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Цитрусовый сок',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Цитрус',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Citrus',
    description: 'Цитрусовый сок - бодрящий цитрусовый вкус',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Агуша мультифрукт',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Мультифрукт',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Agusha',
    description: 'Агуша мультифрукт - сочный мультифруктовый вкус',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Скитлз с кислинкой',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Скитлз, кислинка',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Sour+Skittles',
    description: 'Скитлз с кислинкой - кисло-сладкий вкус',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Киви грейпфрут',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Киви, грейпфрут',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Kiwi+Grapefruit',
    description: 'Киви грейпфрут - кисло-свежий вкус',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Черничная конфета',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Черника, конфета',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Blueberry',
    description: 'Черничная конфета - сладкая черничная конфета',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Смузи банан киви',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Банан, киви',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Banana+Kiwi',
    description: 'Смузи банан киви - нежный смузи',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Дикий персик',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Персик',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Peach',
    description: 'Дикий персик - сочный дикий персик',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Персиковый мармелад',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Персик, мармелад',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Peach+Marmalade',
    description: 'Персиковый мармелад - сладкий персиковый мармелад',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Green - Ментос ментол',
    brand: 'Oggo x Злая монашка',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Ментол',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Green+Mentos',
    description: 'Ментос ментол - освежающий ментоловый вкус',
    rating: 0,
    reviewsCount: 0,
  },

  // ===== OGGO х ЗЛАЯ МОНАШКА 80 mg =====
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Банан земляника',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Банан, земляника',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Banana+Strawberry',
    description: 'Банан земляника - сладкая ягодная классика',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Энергетик лесная малина клубника',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Энергетик, малина, клубника',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Energy+Raspberry',
    description: 'Энергетик лесная малина клубника - бодрящий ягодный вкус',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Кислая яблочная шипучка',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Яблоко, шипучка',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Sour+Apple',
    description: 'Кислая яблочная шипучка - кисло-сладкая шипучка',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Классический энергетик',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Энергетик',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Classic+Energy',
    description: 'Классический энергетик - вкус любимого энергетика',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Лимонад апельсин вишня',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Лимонад, апельсин, вишня',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Lemonade+Orange',
    description: 'Лимонад апельсин вишня - освежающий лимонад',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Кислая апельсиновая конфета',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Апельсин, конфета',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Sour+Orange',
    description: 'Кислая апельсиновая конфета - кисло-сладкая конфета',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Арбузный фреш с клубникой',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Арбуз, клубника',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Watermelon+Strawberry',
    description: 'Арбузный фреш с клубникой - сочный арбуз с клубникой',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Садовые ягоды бабл гам',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Ягоды, бабл гам',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Garden+Berries',
    description: 'Садовые ягоды бабл гам - вкус жевательной резинки с ягодами',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Спелый киви с грейпфрутом',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Киви, грейпфрут',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Kiwi+Grapefruit',
    description: 'Спелый киви с грейпфрутом - кисло-свежий микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Кислый скитлс',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Скитлс',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Sour+Skittles',
    description: 'Кислый скитлс - кислый вкус конфет Skittles',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Вишня кислинка',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Вишня',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Sour+Cherry',
    description: 'Вишня кислинка - кислая вишня',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Арбуз черника',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Арбуз, черника',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Watermelon+Blueberry',
    description: 'Арбуз черника - сочный арбуз с черникой',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Кислое виноград лимонад',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Виноград, лимонад',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Grape+Lemonade',
    description: 'Кислое виноград лимонад - кислый виноградный лимонад',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Кислая жвачка лимон с малиной',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Лимон, малина',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Sour+Gum',
    description: 'Кислая жвачка лимон с малиной - вкус кислой жевачки',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Малина с кислинкой ананас',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Малина, ананас',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Raspberry+Pineapple',
    description: 'Малина с кислинкой ананас - кисло-сладкий микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Кислый лайм клюква',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Лайм, клюква',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Lime+Cranberry',
    description: 'Кислый лайм клюква - кислый ягодный микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Садовая груша смородина',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Груша, смородина',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Pear+Currant',
    description: 'Садовая груша смородина - сочная груша со смородиной',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'OGGO х ЗЛАЯ МОНАШКА - Киви яблоко энергетик',
    brand: 'OGGO х ЗЛАЯ МОНАШКА',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Киви, яблоко, энергетик',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=OGGO+Kiwi+Apple+Energy',
    description: 'Киви яблоко энергетик - бодрящий фруктовый вкус',
    rating: 0,
    reviewsCount: 0,
  },

  // ===== Oggo x Злая монашка Red 80mg =====
  {
    name: 'Oggo x Злая монашка Red - Прайм вишня фризи',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Вишня, фризи',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Cherry',
    description: 'Прайм вишня фризи - вишня со льдом',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Кислый малиновый чупа-чупс',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Малина, чупа-чупс',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Sour+Raspberry',
    description: 'Кислый малиновый чупа-чупс - вкус кислого чупа-чупса',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Зелёный фреш',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Зелёный фреш',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Green+Fresh',
    description: 'Зелёный фреш - освежающий зелёный фреш',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Фреш мандарин гранат',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Мандарин, гранат',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Tangerine',
    description: 'Фреш мандарин гранат - сочный мандарин с гранатом',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Смузи дыня арбуз',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Дыня, арбуз',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Melon+Watermelon',
    description: 'Смузи дыня арбуз - нежный дынно-арбузный смузи',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Кислый киви клюква',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Киви, клюква',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Kiwi+Cranberry',
    description: 'Кислый киви клюква - кислый ягодный микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Лимонад ежевика мята',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Ежевика, мята, лимонад',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Blackberry+Mint',
    description: 'Лимонад ежевика мята - освежающий мятный лимонад',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Малиновый джуси',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Малина',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Juicy+Raspberry',
    description: 'Малиновый джуси - сочная малина',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Арбузная шипучка',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Арбуз, шипучка',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Fizzy+Watermelon',
    description: 'Арбузная шипучка - арбуз с газировкой',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Мохито клубничный',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Мохито, клубника',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Strawberry+Mohito',
    description: 'Мохито клубничный - освежающий мохито с клубникой',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Яблочные леденцы',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Яблоко, леденцы',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Apple+Candy',
    description: 'Яблочные леденцы - сладкие яблочные леденцы',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Доктор пепер вишня',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Доктор пепер, вишня',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Dr+Pepper',
    description: 'Доктор пепер вишня - вкус легендарного напитка',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Клюква лимонад',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Клюква, лимонад',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Cranberry+Lemonade',
    description: 'Клюква лимонад - клюквенный лимонад',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Флэш гранат',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Гранат',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Pomegranate',
    description: 'Флэш гранат - взрыв гранатового вкуса',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Энергетик киви арбуз',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Энергетик, киви, арбуз',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Energy+Kiwi',
    description: 'Энергетик киви арбуз - бодрящий микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Малиновые тропики',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Малина, тропики',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Tropical+Raspberry',
    description: 'Малиновые тропики - малина с тропическими нотками',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Oggo x Злая монашка Red - Медовое яблоко',
    brand: 'Oggo x Злая монашка Red',
    category: 'жидкости',
    price: 450,
    nicotine: 80,
    flavor: 'Мёд, яблоко',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Oggo+Red+Honey+Apple',
    description: 'Медовое яблоко - сладкое яблоко с мёдом',
    rating: 0,
    reviewsCount: 0,
  },

  // ===== Аннима love gold edition 80mg+ boost =====
  {
    name: 'Аннима love gold edition - Смородиновый лимонад',
    brand: 'Аннима love gold edition',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Смородина, лимонад',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Currant+Lemonade',
    description: 'Смородиновый лимонад - освежающий лимонад с смородиной',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Аннима love gold edition - Клубничный мохито',
    brand: 'Аннима love gold edition',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Клубника, мохито',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Strawberry+Mohito',
    description: 'Клубничный мохито - мохито с клубникой',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Аннима love gold edition - Вишнёвый сок',
    brand: 'Аннима love gold edition',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Вишня',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Cherry+Juice',
    description: 'Вишнёвый сок - сочный вишнёвый сок',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Аннима love gold edition - Персиковый сок',
    brand: 'Аннима love gold edition',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Персик',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Peach+Juice',
    description: 'Персиковый сок - спелый персиковый сок',
    rating: 0,
    reviewsCount: 0,
  },

  // ===== Annima love KILLER 80 мг =====
  {
    name: 'Annima love KILLER - Фруктовый тиктак',
    brand: 'Annima love KILLER',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Фруктовый тиктак',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Killer+TicTac',
    description: 'Фруктовый тиктак - вкус конфет TicTac',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love KILLER - Яблочный лимонад',
    brand: 'Annima love KILLER',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Яблоко, лимонад',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Killer+Apple+Lemonade',
    description: 'Яблочный лимонад - освежающий яблочный лимонад',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love KILLER - Ягодная жвачка',
    brand: 'Annima love KILLER',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Ягоды, жвачка',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Killer+Berry+Gum',
    description: 'Ягодная жвачка - вкус ягодной жевательной резинки',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love KILLER - Виноград вишня',
    brand: 'Annima love KILLER',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Виноград, вишня',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Killer+Grape+Cherry',
    description: 'Виноград вишня - сочный виноград с вишней',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love KILLER - Малина апельсин',
    brand: 'Annima love KILLER',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Малина, апельсин',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Killer+Raspberry+Orange',
    description: 'Малина апельсин - ягодно-цитрусовый микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love KILLER - Тропический банан',
    brand: 'Annima love KILLER',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Банан, тропики',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Killer+Tropical+Banana',
    description: 'Тропический банан - банан с тропическими нотками',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love KILLER - Груша малиновая газировка',
    brand: 'Annima love KILLER',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Груша, малина, газировка',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Killer+Pear+Raspberry',
    description: 'Груша малиновая газировка - грушевая газировка с малиной',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love KILLER - Апельсин вишня',
    brand: 'Annima love KILLER',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Апельсин, вишня',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Killer+Orange+Cherry',
    description: 'Апельсин вишня - сладкий цитрус с вишней',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love KILLER - Клубничный коктейль',
    brand: 'Annima love KILLER',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Клубника, коктейль',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Killer+Strawberry+Cocktail',
    description: 'Клубничный коктейль - клубничный молочный коктейль',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love KILLER - Персиковый лимонад',
    brand: 'Annima love KILLER',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Персик, лимонад',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Killer+Peach+Lemonade',
    description: 'Персиковый лимонад - нежный персиковый лимонад',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love KILLER - Виноград алое',
    brand: 'Annima love KILLER',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Виноград, алое',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Killer+Grape+Aloe',
    description: 'Виноград алое - виноград с алое вера',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love KILLER - Ежевичный лимонад',
    brand: 'Annima love KILLER',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Ежевика, лимонад',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Killer+Blackberry+Lemonade',
    description: 'Ежевичный лимонад - освежающий ежевичный лимонад',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love KILLER - Банан клубника',
    brand: 'Annima love KILLER',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Банан, клубника',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Killer+Banana+Strawberry',
    description: 'Банан клубника - сладкий банан с клубникой',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love KILLER - Ананас апельсин',
    brand: 'Annima love KILLER',
    category: 'жидкости',
    price: 400,
    nicotine: 80,
    flavor: 'Ананас, апельсин',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Killer+Pineapple+Orange',
    description: 'Ананас апельсин - экзотический цитрус с ананасом',
    rating: 0,
    reviewsCount: 0,
  },

  // ===== Annima love Sour 60 mg =====
  {
    name: 'Annima love Sour - Кислая яблоко киви',
    brand: 'Annima love Sour',
    category: 'жидкости',
    price: 400,
    nicotine: 60,
    flavor: 'Яблоко, киви',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Sour+Apple+Kiwi',
    description: 'Кислая яблоко киви - кислый фруктовый микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love Sour - Кислый вишня гранат',
    brand: 'Annima love Sour',
    category: 'жидкости',
    price: 400,
    nicotine: 60,
    flavor: 'Вишня, гранат',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Sour+Cherry+Pomegranate',
    description: 'Кислый вишня гранат - кисло-сладкий микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love Sour - Кислые мармеладные червяки',
    brand: 'Annima love Sour',
    category: 'жидкости',
    price: 400,
    nicotine: 60,
    flavor: 'Мармелад, червяки',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Sour+Worms',
    description: 'Кислые мармеладные червяки - вкус кислых мармеладных червяков',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Annima love Sour - Кислый арбуз малина',
    brand: 'Annima love Sour',
    category: 'жидкости',
    price: 400,
    nicotine: 60,
    flavor: 'Арбуз, малина',
    weight: 30,
    inStock: true,
    stockQuantity: 50,
    image: 'https://via.placeholder.com/200x200?text=Annima+Sour+Watermelon+Raspberry',
    description: 'Кислый арбуз малина - кислая арбузно-малиновая классика',
    rating: 0,
    reviewsCount: 0,
  },

  // ===== Самоубийца v2 25000 тяг =====
  {
    name: 'Самоубийца v2 - Кислая киви виноград',
    brand: 'Самоубийца v2',
    category: 'одноразки',
    price: 1300,
    nicotine: 0,
    flavor: 'Киви, виноград',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Samoubiitsa+V2+Kiwi+Grape',
    description: 'Кислая киви виноград - 25000 тяг, кислый фруктовый микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Самоубийца v2 - Смородина личи',
    brand: 'Самоубийца v2',
    category: 'одноразки',
    price: 1300,
    nicotine: 0,
    flavor: 'Смородина, личи',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Samoubiitsa+V2+Currant+Lychee',
    description: 'Смородина личи - 25000 тяг, экзотический микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Самоубийца v2 - Кислое яблоко с ежевикой',
    brand: 'Самоубийца v2',
    category: 'одноразки',
    price: 1300,
    nicotine: 0,
    flavor: 'Яблоко, ежевика',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Samoubiitsa+V2+Sour+Apple+Blackberry',
    description: 'Кислое яблоко с ежевикой - 25000 тяг, кисло-сладкий вкус',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Самоубийца v2 - Кислая малина клюква',
    brand: 'Самоубийца v2',
    category: 'одноразки',
    price: 1300,
    nicotine: 0,
    flavor: 'Малина, клюква',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Samoubiitsa+V2+Sour+Raspberry+Cranberry',
    description: 'Кислая малина клюква - 25000 тяг, кислый ягодный микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Самоубийца v2 - Кислый вишневый холс',
    brand: 'Самоубийца v2',
    category: 'одноразки',
    price: 1300,
    nicotine: 0,
    flavor: 'Вишня',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Samoubiitsa+V2+Sour+Cherry',
    description: 'Кислый вишневый холс - 25000 тяг, ледяная вишня',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Самоубийца v2 - Кола лесные ягоды',
    brand: 'Самоубийца v2',
    category: 'одноразки',
    price: 1300,
    nicotine: 0,
    flavor: 'Кола, лесные ягоды',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Samoubiitsa+V2+Cola+Berries',
    description: 'Кола лесные ягоды - 25000 тяг, кола с ягодами',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Самоубийца v2 - Виноград смородина мята',
    brand: 'Самоубийца v2',
    category: 'одноразки',
    price: 1300,
    nicotine: 0,
    flavor: 'Виноград, смородина, мята',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Samoubiitsa+V2+Grape+Currant+Mint',
    description: 'Виноград смородина мята - 25000 тяг, освежающий микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Самоубийца v2 - Арбузно дынный фреш',
    brand: 'Самоубийца v2',
    category: 'одноразки',
    price: 1300,
    nicotine: 0,
    flavor: 'Арбуз, дыня',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Samoubiitsa+V2+Watermelon+Melon',
    description: 'Арбузно дынный фреш - 25000 тяг, сочный арбуз с дыней',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Самоубийца v2 - Кислая вишня смородина',
    brand: 'Самоубийца v2',
    category: 'одноразки',
    price: 1300,
    nicotine: 0,
    flavor: 'Вишня, смородина',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Samoubiitsa+V2+Sour+Cherry+Currant',
    description: 'Кислая вишня смородина - 25000 тяг, кислый ягодный вкус',
    rating: 0,
    reviewsCount: 0,
  },

  // ===== Грех самоубийца Sour 20000 тяг =====
  {
    name: 'Грех самоубийца Sour - Малина ежевика черника',
    brand: 'Грех самоубийца Sour',
    category: 'одноразки',
    price: 1200,
    nicotine: 0,
    flavor: 'Малина, ежевика, черника',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Sour+Raspberry+Blackberry',
    description: 'Малина ежевика черника - 20000 тяг, ягодный микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Sour - Кислая вишня редбулл белая смородина',
    brand: 'Грех самоубийца Sour',
    category: 'одноразки',
    price: 1200,
    nicotine: 0,
    flavor: 'Вишня, редбулл, смородина',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Sour+Cherry+Redbull',
    description: 'Кислая вишня редбулл белая смородина - 20000 тяг, бодрящий микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Sour - Малина клюква зелёный виноград',
    brand: 'Грех самоубийца Sour',
    category: 'одноразки',
    price: 1200,
    nicotine: 0,
    flavor: 'Малина, клюква, виноград',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Sour+Raspberry+Cranberry',
    description: 'Малина клюква зелёный виноград - 20000 тяг, кислый фруктовый микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Sour - Ежевика кислая вишня',
    brand: 'Грех самоубийца Sour',
    category: 'одноразки',
    price: 1200,
    nicotine: 0,
    flavor: 'Ежевика, вишня',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Sour+Blackberry+Cherry',
    description: 'Ежевика кислая вишня - 20000 тяг, кислый ягодный микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Sour - Клюква красная смородина лайм',
    brand: 'Грех самоубийца Sour',
    category: 'одноразки',
    price: 1200,
    nicotine: 0,
    flavor: 'Клюква, смородина, лайм',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Sour+Cranberry+Currant+Lime',
    description: 'Клюква красная смородина лайм - 20000 тяг, кисло-цитрусовый микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Sour - Чёрная смородина вишня лайм',
    brand: 'Грех самоубийца Sour',
    category: 'одноразки',
    price: 1200,
    nicotine: 0,
    flavor: 'Смородина, вишня, лайм',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Sour+Blackcurrant+Cherry+Lime',
    description: 'Чёрная смородина вишня лайм - 20000 тяг, кислый ягодно-цитрусовый микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Sour - Малина черника земляника',
    brand: 'Грех самоубийца Sour',
    category: 'одноразки',
    price: 1200,
    nicotine: 0,
    flavor: 'Малина, черника, земляника',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Sour+Raspberry+Blueberry',
    description: 'Малина черника земляника - 20000 тяг, сладкий ягодный микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Sour - Скитлз виноград малина',
    brand: 'Грех самоубийца Sour',
    category: 'одноразки',
    price: 1200,
    nicotine: 0,
    flavor: 'Скитлз, виноград, малина',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Sour+Skittles+Grape',
    description: 'Скитлз виноград малина - 20000 тяг, вкус конфет Skittles',
    rating: 0,
    reviewsCount: 0,
  },

  // ===== Грех самоубийца Ice 30000 тяг =====
  {
    name: 'Грех самоубийца Ice - Черника малина красная смородина лёд',
    brand: 'Грех самоубийца Ice',
    category: 'одноразки',
    price: 1350,
    nicotine: 0,
    flavor: 'Черника, малина, смородина, лёд',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Ice+Blueberry+Raspberry',
    description: 'Черника малина красная смородина лёд - 30000 тяг, ледяной ягодный микс',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Ice - Клубника голубика лёд',
    brand: 'Грех самоубийца Ice',
    category: 'одноразки',
    price: 1350,
    nicotine: 0,
    flavor: 'Клубника, голубика, лёд',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Ice+Strawberry+Blueberry',
    description: 'Клубника голубика лёд - 30000 тяг, ледяная ягода',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Ice - Сок земляники смородинный лёд',
    brand: 'Грех самоубийца Ice',
    category: 'одноразки',
    price: 1350,
    nicotine: 0,
    flavor: 'Земляника, смородина, лёд',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Ice+Strawberry+Currant',
    description: 'Сок земляники смородинный лёд - 30000 тяг, ледяной ягодный сок',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Ice - Земляника энергетик лёд',
    brand: 'Грех самоубийца Ice',
    category: 'одноразки',
    price: 1350,
    nicotine: 0,
    flavor: 'Земляника, энергетик, лёд',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Ice+Strawberry+Energy',
    description: 'Земляника энергетик лёд - 30000 тяг, бодрящий ледяной вкус',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Ice - Морозные лесные ягоды',
    brand: 'Грех самоубийца Ice',
    category: 'одноразки',
    price: 1350,
    nicotine: 0,
    flavor: 'Лесные ягоды, лёд',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Ice+Forest+Berries',
    description: 'Морозные лесные ягоды - 30000 тяг, ледяные лесные ягоды',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Ice - Холодный фруктовый скитлз',
    brand: 'Грех самоубийца Ice',
    category: 'одноразки',
    price: 1350,
    nicotine: 0,
    flavor: 'Скитлз, лёд',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Ice+Cold+Skittles',
    description: 'Холодный фруктовый скитлз - 30000 тяг, ледяные конфеты',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Ice - Зелёный виноград ледяной лайм черника мята',
    brand: 'Грех самоубийца Ice',
    category: 'одноразки',
    price: 1350,
    nicotine: 0,
    flavor: 'Виноград, лайм, черника, мята, лёд',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Ice+Green+Grape+Mint',
    description: 'Зелёный виноград ледяной лайм черника мята - 30000 тяг, ледяной мультивкус',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Ice - Редбулл ледяная черника мята',
    brand: 'Грех самоубийца Ice',
    category: 'одноразки',
    price: 1350,
    nicotine: 0,
    flavor: 'Редбулл, черника, мята, лёд',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Ice+Redbull+Mint',
    description: 'Редбулл ледяная черника мята - 30000 тяг, бодрящий ледяной вкус',
    rating: 0,
    reviewsCount: 0,
  },
  {
    name: 'Грех самоубийца Ice - Ежевика ледяная груша',
    brand: 'Грех самоубийца Ice',
    category: 'одноразки',
    price: 1350,
    nicotine: 0,
    flavor: 'Ежевика, груша, лёд',
    weight: 0,
    inStock: true,
    stockQuantity: 30,
    image: 'https://via.placeholder.com/200x200?text=Greh+Ice+Blackberry+Pear',
    description: 'Ежевика ледяная груша - 30000 тяг, ледяная груша с ежевикой',
    rating: 0,
    reviewsCount: 0,
  },
];

// ============ Администратор ============
const admin = {
  telegramId: '123456789',
  username: 'admin',
  firstName: 'Администратор',
  role: 'admin',
};

// ============ Заполнение БД ============
async function seedDB() {
  try {
    console.log('🔄 Подключение к MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Подключено к MongoDB');
    console.log(`📊 База данных: ${mongoose.connection.name}`);

    console.log('🗑️ Очистка коллекций...');
    await Product.deleteMany({});
    await Order.deleteMany({});
    await User.deleteMany({});
    console.log('✅ Коллекции очищены');

    console.log('📦 Добавление товаров...');
    const insertedProducts = await Product.insertMany(products);
    console.log(`✅ Добавлено ${insertedProducts.length} товаров`);

    console.log('👤 Добавление администратора...');
    await User.create(admin);
    console.log('✅ Добавлен администратор');

    console.log('\n🎉 База данных успешно заполнена!');
    console.log(`📊 Итог: ${insertedProducts.length} товаров, 1 администратор`);
    console.log(`📋 Категории:`);
    console.log(`   - Жидкости: ${products.filter(p => p.category === 'жидкости').length}`);
    console.log(`   - Одноразки: ${products.filter(p => p.category === 'одноразки').length}`);
    
    process.exit(0);
  } catch (error) {
    console.error('❌ Ошибка:', error.message);
    process.exit(1);
  }
}

seedDB();